# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c770266dd035ce14a03c9a61f1db6be3f9915a6625e5569256688086399add6ff569cedb1ad69b050011bf441f5bd88af73905c60e59846f75be44b50f5589e

test:
  secret_key_base: c6aae72b31badde9da1a9d0dfba10a888d971c69a848dcc07f6174521e3e0ce1a631415b422eaac9cae96bd342d9c87e8d52177b6f559d876a64874bc1becc8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
